name: cognite_flutter_demo
description: A demo application for Cognite CDF
homepage: https://github.com/gregertw/cognite_flutter_demo
version: 0.3.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_appauth: ^1.0.0+1
  cupertino_icons: ^1.0.3
  meta: ^1.3.0
  provider: ^5.0.0
  logger: ^1.0.0
  shared_preferences: ^2.0.6
  firebase_core: ^1.2.1
  firebase_analytics: ^8.1.1
  firebase_crashlytics: ^2.0.5
  overlay_support: ^1.2.1
  url_launcher: ^6.0.6
  cognite_cdf_sdk: ^0.2.0-nullsafety
  syncfusion_flutter_charts: ^19.1.66+1
  syncfusion_flutter_core: ^19.1.66
  syncfusion_flutter_sliders: ^19.1.66-beta
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_launcher_icons: ^0.9.0
  convert: any
  mockito: ^5.0.9
    

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/actingweb-header-small.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf
flutter_intl:
  enabled: true
