name: cognite_cdf_demo
description: A demo application for Cognite CDF
homepage: https://docs.cognite.com/dev/
version: 0.2.0
publish_to: none

environment:
  sdk: ">2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_appauth: ^0.9.2+5
  cupertino_icons: ^1.0.0
  meta: ^1.1.8
  provider: ^4.3.2+2
  logger: ^0.9.4
  shared_preferences: ^0.5.12
  firebase_analytics: ^6.0.1
  firebase_crashlytics: ^0.2.1
  firebase_analytics_web: ^0.1.1
  firebase_core_web: ^0.2.1+1
  flushbar: ^1.10.4
  cognite_cdf_sdk: ^0.1.2-dev.4
  syncfusion_flutter_charts: #^18.3.51
    path: ../flutter-widgets/packages/syncfusion_flutter_charts
  syncfusion_flutter_core: #^18.3.51
    path: ../flutter-widgets/packages/syncfusion_flutter_core
  syncfusion_flutter_sliders: #^18.3.51
    path: ../flutter-widgets/packages/syncfusion_flutter_sliders
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_launcher_icons: ^0.8.1
  intl_translation: ^0.17.10+1
  convert: any
  mockito: ^4.1.1 #Lock down as 4.1.2 seems to rely on a null-safe lib
    

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/actingweb-header-small.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf
flutter_intl:
  enabled: true
